### ISSUE TITLE
Error when trying to open pcap-file.

### ISSUE THREAD

**Issue by ArneFilipovic** [FlUxIuS/V2GInjector#5] opened 2021-01-26 16:22 UTC
When I try to open a v2g-pcap-file with Network().pcap('someFile.pcap')

I get the following error within the scapy module:

**"C:\Users\SomeName\anaconda3\envs\V2G_Analysis27\lib\site-packages\scapy\packet.py", line 498, in __div__
    return other.__rdiv__(self)
AttributeError: 'NoneType' object has no attribute '__rdiv__'**

I got the V2Gdecoder file from: 
(https://github.com/FlUxIuS/V2Gdecoder/releases)

and started the V2Gdecoder .jar  file before with:
 java -jar V2Gdecoder.jar -w

I am running:
python 3.8.5
scapy 2.4.4
colorama 0.4.4
requests 2.25.0

I tried it with python 2.7 as well but got the same error. 

Is this a compatibility issue? I try to run the programm with Win 10. 

cheers Arne

**Comment by FlUxIuS** [comment] 2021-01-26 16:49
Hi Arne,

Can you upload the pcap in this issue? Like that, I can see where the issue is because. Here Scapy seems to have trouble reading it but I need more input to see the problem.

I didn't try the tool in Windows, but I can find some time to support it. 

Thanks in advance!

Cheers,
Seb

**Comment by ArneFilipovic** [comment] 2021-01-27 08:37
Hi Sébastien,

thank you for getting back to me so quickly. The example pcap is attached to this message. 

I think my trouble comes from not getting the V2Gdecoder to work proberly. Where does the .jar needs to be located in respect to the  other files in the V2Ginjector directory? 

[Example.zip](https://github.com/FlUxIuS/V2GInjector/files/5878535/Example.zip)

cheers Arne

**Comment by FlUxIuS** [comment] 2022-01-31 21:26
Reinstalling from scratch, I think it was a problem of the schemas repository not being found by the decoder, and no Warning message are displayed -_-'

That is fixed with the new update!

**Closed as completed by FlUxIuS** 2022-01-31 21:26 UTC
